# must accept EULA the first time that the image is started

# docker run cribl/universalforwarder:8.0.5
# Options on how to review the EULA and accept it: 
# 1. docker run -it cribl/universalforwarder:8.0.5
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/splunkuniversalforwarder:8.0.5 

# Support for Docker Compose v3, https://docs.docker.com/compose/overview/
version: '3'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  splunkuniversalforwarder:
#    build: .
    hostname: splunkuniversalforwarder
    image: cribl/universalforwarder:8.0.5
#    environment:
#      SPLUNK_START_ARGS: --accept-license
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"

